name: Build and Release ileapy

on:
  push:
    branches: 
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build project
      run: msbuild ileapy.csproj /p:Configuration=Release /p:Platform=AnyCPU /p:OutputPath=bin\Release
    
    - name: Upload Release to GitHub
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: ileapy Release v${{ github.run_number }}
        body: |
          Standalone executable for ileapy.
          Just download and run the .exe file.
          Note that this is only in Beta phase. 
          Any issues that may occur should be announce to get fixed.
        files: ./bin/Release/*.exe
